version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - "PORT=8080"
      - "LOG_LEVEL=INFO"
      - "LOGIN_DURATION_IN_SECOND=86400"
      - "MAX_REQUEST_BODY_SIZE=10000000"
      - "DATABASE_DRIVER=postgres"
      - "DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?sslmode=disable"
      - "MINIO_ENDPOINT=minio:9000"
      - "MINIO_ACCESS_KEY=${MINIO_ROOT_USER}"
      - "MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}"
      - "MINIO_BUCKET=${MINIO_BUCKET}"
    depends_on:
      - miniocreatebuckets
      - database

  database:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    volumes:
      - database:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d library'"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 5s

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    environment:
      - "MINIO_ROOT_USER=${MINIO_ROOT_USER}"
      - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}"
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data

  miniocreatebuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/${MINIO_BUCKET};
      /usr/bin/mc anonymous set public myminio/${MINIO_BUCKET};
      exit 0;
      "

volumes:
  minio:
  database:
